# Generated by Django 4.2.4 on 2023-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
